name: "pre-release"

on:
  push:
    branches:
      - "autobuild_linux"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: "Build & test"
        run: cd distributions; sudo build-debian-package-auto.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.deb
